const themesData = [
  {
    id: 1,
    title: '1) 자기소개 & 가족',
    icon: '🆔',
    words: [
      // --- 기본 신상 정보 (이름, 나이) ---
      { ch: '叫', py: 'jiào', mean: '부르다, ~라고 하다' },
      { ch: '是', py: 'shì', mean: '~이다' },
      { ch: '姓', py: 'xìng', mean: '성(이 ~이다)' },
      { ch: '名字', py: 'míngzi', mean: '이름' },
      { ch: '出生', py: 'chūshēng', mean: '출생하다' },
      { ch: '于', py: 'yú', mean: '~에 (장소/시간)' },
      { ch: '生日', py: 'shēngrì', mean: '생일' },
      { ch: '岁', py: 'suì', mean: '살, 세 (나이)' },
      { ch: '年', py: 'nián', mean: '년' },
      { ch: '月', py: 'yuè', mean: '월' },
      { ch: '号', py: 'hào', mean: '일 (날짜)' },
      { ch: '几', py: 'jǐ', mean: '몇' },

      // --- 가족 호칭 (부부) ---
      { ch: '爱人', py: 'àiren', mean: '배우자' },
      { ch: '老公', py: 'lǎogōng', mean: '남편 (구어)' },
      { ch: '老婆', py: 'lǎopo', mean: '아내 (구어)' },
      { ch: '丈夫', py: 'zhàngfu', mean: '남편' },
      { ch: '妻子', py: 'qīzi', mean: '아내' },
      { ch: '先生', py: 'xiānsheng', mean: '선생님, 남편' },
      { ch: '太太', py: 'tàitai', mean: '부인, 아내' },

      // --- 가족 호칭 (혈연) ---
      { ch: '爷爷', py: 'yéye', mean: '할아버지' },
      { ch: '奶奶', py: 'nǎinai', mean: '할머니' },
      { ch: '爸爸', py: 'bàba', mean: '아빠' },
      { ch: '妈妈', py: 'māma', mean: '엄마' },
      { ch: '哥哥', py: 'gēge', mean: '형, 오빠' },
      { ch: '姐姐', py: 'jiějie', mean: '누나, 언니' },
      { ch: '弟弟', py: 'dìdi', mean: '남동생' },
      { ch: '妹妹', py: 'mèimei', mean: '여동생' },
      { ch: '儿子', py: 'érzi', mean: '아들' },
      { ch: '女儿', py: "nǚ'ér", mean: '딸' },
      { ch: '孩子', py: 'háizi', mean: '아이' },
      { ch: '家人', py: 'jiārén', mean: '가족' },
      { ch: '独生子女', py: 'dúshēng zǐnǚ', mean: '외동' },

      // --- 가족 수 및 양사 ---
      { ch: '口', py: 'kǒu', mean: '(가족 수 세는) 명' },
      { ch: '个', py: 'gè', mean: '개, 명 (양사)' },
      { ch: '和', py: 'hé', mean: '~와, ~하고' },

      // --- 직업 및 학교 ---
      { ch: '工作', py: 'gōngzuò', mean: '일하다, 직장' },
      { ch: '在', py: 'zài', mean: '~에 있다, ~에서' },
      { ch: '地方', py: 'dìfang', mean: '장소' },
      { ch: '公司', py: 'gōngsī', mean: '회사' },
      { ch: '上班族', py: 'shàngbānzú', mean: '직장인' },
      { ch: '学生', py: 'xuéshēng', mean: '학생' },
      { ch: '大学', py: 'dàxué', mean: '대학교' },
      { ch: '研究生', py: 'yánjiūshēng', mean: '대학원생' },
      { ch: '年级', py: 'niánjí', mean: '학년' },
      { ch: '毕业', py: 'bìyè', mean: '졸업하다' },
    ],
  },
  {
    id: 2,
    title: '2) 장소/위치/사물 표현',
    icon: '📍',
    words: [
      // --- (1) 장소 (Place) ---
      { ch: '商店', py: 'shāngdiàn', mean: '상점' },
      { ch: '百货商店', py: 'bǎihuò shāngdiàn', mean: '백화점' },
      { ch: '咖啡厅', py: 'kāfēi tīng', mean: '카페' },
      { ch: '快餐店', py: 'kuàicān diàn', mean: '패스트푸드점' },
      { ch: '麦当劳', py: 'Màidāngláo', mean: '맥도날드' },
      { ch: '肯德基', py: 'Kěndéjī', mean: 'KFC' },
      { ch: '便利店', py: 'biànlìdiàn', mean: '편의점' },
      { ch: '电影院', py: 'diànyǐngyuàn', mean: '영화관' },
      { ch: '邮局', py: 'yóujú', mean: '우체국' },
      { ch: '超市', py: 'chāoshì', mean: '슈퍼마켓' },
      { ch: '饭馆', py: 'fànguǎn', mean: '식당' },
      { ch: '餐厅', py: 'cāntīng', mean: '레스토랑' },
      { ch: '公园', py: 'gōngyuán', mean: '공원' },
      { ch: '动物园', py: 'dòngwùyuán', mean: '동물원' },
      { ch: '银行', py: 'yínháng', mean: '은행' },
      { ch: '公司', py: 'gōngsī', mean: '회사' },
      { ch: '医院', py: 'yīyuàn', mean: '병원' },
      { ch: '药店', py: 'yàodiàn', mean: '약국' },
      { ch: '健身房', py: 'jiànshēnfáng', mean: '헬스장' },
      { ch: '游泳池', py: 'yóuyǒngchí', mean: '수영장' },
      { ch: '宾馆', py: 'bīnguǎn', mean: '호텔' },
      { ch: '书店', py: 'shūdiàn', mean: '서점' },
      { ch: '教室', py: 'jiàoshì', mean: '교실' },
      { ch: '图书馆', py: 'túshūguǎn', mean: '도서관' },
      { ch: '花店', py: 'huādiàn', mean: '꽃집' },
      { ch: '学校', py: 'xuéxiào', mean: '학교' },
      { ch: '操场', py: 'cāochǎng', mean: '운동장' },
      { ch: '宿舍', py: 'sùshè', mean: '기숙사' },
      { ch: '房间', py: 'fángjiān', mean: '방' },
      { ch: '办公室', py: 'bàngōngshì', mean: '사무실' },
      { ch: '网吧', py: 'wǎngbā', mean: 'PC방' },

      // --- (2) 방위사 (Direction) ---
      { ch: '上边', py: 'shàngbian', mean: '위' },
      { ch: '下边', py: 'xiàbian', mean: '아래' },
      { ch: '右边', py: 'yòubian', mean: '오른쪽' },
      { ch: '左边', py: 'zuǒbian', mean: '왼쪽' },
      { ch: '前边', py: 'qiánbian', mean: '앞' },
      { ch: '后边', py: 'hòubian', mean: '뒤' },
      { ch: '里边', py: 'lǐbian', mean: '안' },
      { ch: '外边', py: 'wàibian', mean: '밖' },
      { ch: '旁边', py: 'pángbian', mean: '옆' },
      { ch: '对面', py: 'duìmiàn', mean: '맞은편' },
      { ch: '中间', py: 'zhōngjiān', mean: '가운데' },
      { ch: '东边', py: 'dōngbian', mean: '동쪽' },
      { ch: '西边', py: 'xībian', mean: '서쪽' },
      { ch: '南边', py: 'nánbian', mean: '남쪽' },
      { ch: '北边', py: 'běibian', mean: '북쪽' },

      // --- (3) 양사 (Measure Words) ---
      { ch: '个', py: 'gè', mean: '개 (범용 양사)' },
      { ch: '杯', py: 'bēi', mean: '잔' },
      { ch: '本', py: 'běn', mean: '권 (책)' },
      { ch: '件', py: 'jiàn', mean: '벌 (옷), 건 (사건)' },
      { ch: '辆', py: 'liàng', mean: '대 (차량)' },
      { ch: '瓶', py: 'píng', mean: '병' },
      { ch: '双', py: 'shuāng', mean: '켤레 (신발, 젓가락)' },
      { ch: '条', py: 'tiáo', mean: '줄, 마리 (긴 것)' },
      { ch: '台', py: 'tái', mean: '대 (기계)' },
      { ch: '只', py: 'zhī', mean: '마리 (동물)' },

      // --- (4) 장소 관련 사물 (Objects) ---
      { ch: '牛奶', py: 'niúnǎi', mean: '우유' },
      { ch: '面包', py: 'miànbāo', mean: '빵' },
      { ch: '花瓶', py: 'huāpíng', mean: '꽃병' },
      { ch: '桌子', py: 'zhuōzi', mean: '책상, 탁자' },
      { ch: '椅子', py: 'yǐzi', mean: '의자' },
      { ch: '沙发', py: 'shāfā', mean: '소파' },
      { ch: '报纸', py: 'bàozhǐ', mean: '신문' },
      { ch: '猫', py: 'māo', mean: '고양이' },
      { ch: '小狗', py: 'xiǎogǒu', mean: '강아지' },
      { ch: '手表', py: 'shǒubiǎo', mean: '손목시계' },
      { ch: '眼镜', py: 'yǎnjìng', mean: '안경' },
      { ch: '手机', py: 'shǒujī', mean: '휴대폰' },
      { ch: '打电话', py: 'dǎ diànhuà', mean: '전화하다' },
      { ch: '电视', py: 'diànshì', mean: '텔레비전' },
    ],
  },
];
