const themesData = [
  {
    id: 1,
    title: '1) 자기소개 & 가족',
    icon: '🆔',
    words: [
      // --- 기본 신상 정보 (이름, 나이) ---
      { ch: '叫', py: 'jiào', mean: '부르다, ~라고 하다' },
      { ch: '是', py: 'shì', mean: '~이다' },
      { ch: '姓', py: 'xìng', mean: '성(이 ~이다)' },
      { ch: '名字', py: 'míngzi', mean: '이름' },
      { ch: '出生', py: 'chūshēng', mean: '출생하다' },
      { ch: '于', py: 'yú', mean: '~에 (장소/시간)' },
      { ch: '生日', py: 'shēngrì', mean: '생일' },
      { ch: '岁', py: 'suì', mean: '살, 세 (나이)' },
      { ch: '年', py: 'nián', mean: '년' },
      { ch: '月', py: 'yuè', mean: '월' },
      { ch: '号', py: 'hào', mean: '일 (날짜)' },
      { ch: '几', py: 'jǐ', mean: '몇' },

      // --- 가족 호칭 (부부) ---
      { ch: '爱人', py: 'àiren', mean: '배우자' },
      { ch: '老公', py: 'lǎogōng', mean: '남편 (구어)' },
      { ch: '老婆', py: 'lǎopo', mean: '아내 (구어)' },
      { ch: '丈夫', py: 'zhàngfu', mean: '남편' },
      { ch: '妻子', py: 'qīzi', mean: '아내' },
      { ch: '先生', py: 'xiānsheng', mean: '선생님, 남편' },
      { ch: '太太', py: 'tàitai', mean: '부인, 아내' },

      // --- 가족 호칭 (혈연) ---
      { ch: '爷爷', py: 'yéye', mean: '할아버지' },
      { ch: '奶奶', py: 'nǎinai', mean: '할머니' },
      { ch: '爸爸', py: 'bàba', mean: '아빠' },
      { ch: '妈妈', py: 'māma', mean: '엄마' },
      { ch: '哥哥', py: 'gēge', mean: '형, 오빠' },
      { ch: '姐姐', py: 'jiějie', mean: '누나, 언니' },
      { ch: '弟弟', py: 'dìdi', mean: '남동생' },
      { ch: '妹妹', py: 'mèimei', mean: '여동생' },
      { ch: '儿子', py: 'érzi', mean: '아들' },
      { ch: '女儿', py: "nǚ'ér", mean: '딸' },
      { ch: '孩子', py: 'háizi', mean: '아이' },
      { ch: '家人', py: 'jiārén', mean: '가족' },
      { ch: '独生子女', py: 'dúshēng zǐnǚ', mean: '외동' },

      // --- 가족 수 및 양사 ---
      { ch: '口', py: 'kǒu', mean: '(가족 수 세는) 명' },
      { ch: '个', py: 'gè', mean: '개, 명 (양사)' },
      { ch: '和', py: 'hé', mean: '~와, ~하고' },

      // --- 직업 및 학교 ---
      { ch: '工作', py: 'gōngzuò', mean: '일하다, 직장' },
      { ch: '在', py: 'zài', mean: '~에 있다, ~에서' },
      { ch: '地方', py: 'dìfang', mean: '장소' },
      { ch: '公司', py: 'gōngsī', mean: '회사' },
      { ch: '上班族', py: 'shàngbānzú', mean: '직장인' },
      { ch: '学生', py: 'xuéshēng', mean: '학생' },
      { ch: '大学', py: 'dàxué', mean: '대학교' },
      { ch: '研究生', py: 'yánjiūshēng', mean: '대학원생' },
      { ch: '年级', py: 'niánjí', mean: '학년' },
      { ch: '毕业', py: 'bìyè', mean: '졸업하다' },
    ],
  },
  {
    id: 2,
    title: '2) 장소/위치/사물 표현',
    icon: '📍',
    words: [
      // --- (1) 장소 (Place) ---
      { ch: '商店', py: 'shāngdiàn', mean: '상점' },
      { ch: '百货商店', py: 'bǎihuò shāngdiàn', mean: '백화점' },
      { ch: '咖啡厅', py: 'kāfēi tīng', mean: '카페' },
      { ch: '快餐店', py: 'kuàicān diàn', mean: '패스트푸드점' },
      { ch: '麦当劳', py: 'Màidāngláo', mean: '맥도날드' },
      { ch: '肯德基', py: 'Kěndéjī', mean: 'KFC' },
      { ch: '便利店', py: 'biànlìdiàn', mean: '편의점' },
      { ch: '电影院', py: 'diànyǐngyuàn', mean: '영화관' },
      { ch: '邮局', py: 'yóujú', mean: '우체국' },
      { ch: '超市', py: 'chāoshì', mean: '슈퍼마켓' },
      { ch: '饭馆', py: 'fànguǎn', mean: '식당' },
      { ch: '餐厅', py: 'cāntīng', mean: '레스토랑' },
      { ch: '公园', py: 'gōngyuán', mean: '공원' },
      { ch: '动物园', py: 'dòngwùyuán', mean: '동물원' },
      { ch: '银行', py: 'yínháng', mean: '은행' },
      { ch: '公司', py: 'gōngsī', mean: '회사' },
      { ch: '医院', py: 'yīyuàn', mean: '병원' },
      { ch: '药店', py: 'yàodiàn', mean: '약국' },
      { ch: '健身房', py: 'jiànshēnfáng', mean: '헬스장' },
      { ch: '游泳池', py: 'yóuyǒngchí', mean: '수영장' },
      { ch: '宾馆', py: 'bīnguǎn', mean: '호텔' },
      { ch: '书店', py: 'shūdiàn', mean: '서점' },
      { ch: '教室', py: 'jiàoshì', mean: '교실' },
      { ch: '图书馆', py: 'túshūguǎn', mean: '도서관' },
      { ch: '花店', py: 'huādiàn', mean: '꽃집' },
      { ch: '学校', py: 'xuéxiào', mean: '학교' },
      { ch: '操场', py: 'cāochǎng', mean: '운동장' },
      { ch: '宿舍', py: 'sùshè', mean: '기숙사' },
      { ch: '房间', py: 'fángjiān', mean: '방' },
      { ch: '办公室', py: 'bàngōngshì', mean: '사무실' },
      { ch: '网吧', py: 'wǎngbā', mean: 'PC방' },

      // --- (2) 방위사 (Direction) ---
      { ch: '上边', py: 'shàngbian', mean: '위' },
      { ch: '下边', py: 'xiàbian', mean: '아래' },
      { ch: '右边', py: 'yòubian', mean: '오른쪽' },
      { ch: '左边', py: 'zuǒbian', mean: '왼쪽' },
      { ch: '前边', py: 'qiánbian', mean: '앞' },
      { ch: '后边', py: 'hòubian', mean: '뒤' },
      { ch: '里边', py: 'lǐbian', mean: '안' },
      { ch: '外边', py: 'wàibian', mean: '밖' },
      { ch: '旁边', py: 'pángbian', mean: '옆' },
      { ch: '对面', py: 'duìmiàn', mean: '맞은편' },
      { ch: '中间', py: 'zhōngjiān', mean: '가운데' },
      { ch: '东边', py: 'dōngbian', mean: '동쪽' },
      { ch: '西边', py: 'xībian', mean: '서쪽' },
      { ch: '南边', py: 'nánbian', mean: '남쪽' },
      { ch: '北边', py: 'běibian', mean: '북쪽' },

      // --- (3) 양사 (Measure Words) ---
      { ch: '个', py: 'gè', mean: '개 (범용 양사)' },
      { ch: '杯', py: 'bēi', mean: '잔' },
      { ch: '本', py: 'běn', mean: '권 (책)' },
      { ch: '件', py: 'jiàn', mean: '벌 (옷), 건 (사건)' },
      { ch: '辆', py: 'liàng', mean: '대 (차량)' },
      { ch: '瓶', py: 'píng', mean: '병' },
      { ch: '双', py: 'shuāng', mean: '켤레 (신발, 젓가락)' },
      { ch: '条', py: 'tiáo', mean: '줄, 마리 (긴 것)' },
      { ch: '台', py: 'tái', mean: '대 (기계)' },
      { ch: '只', py: 'zhī', mean: '마리 (동물)' },

      // --- (4) 장소 관련 사물 (Objects) ---
      { ch: '牛奶', py: 'niúnǎi', mean: '우유' },
      { ch: '面包', py: 'miànbāo', mean: '빵' },
      { ch: '花瓶', py: 'huāpíng', mean: '꽃병' },
      { ch: '桌子', py: 'zhuōzi', mean: '책상, 탁자' },
      { ch: '椅子', py: 'yǐzi', mean: '의자' },
      { ch: '沙发', py: 'shāfā', mean: '소파' },
      { ch: '报纸', py: 'bàozhǐ', mean: '신문' },
      { ch: '猫', py: 'māo', mean: '고양이' },
      { ch: '小狗', py: 'xiǎogǒu', mean: '강아지' },
      { ch: '手表', py: 'shǒubiǎo', mean: '손목시계' },
      { ch: '眼镜', py: 'yǎnjìng', mean: '안경' },
      { ch: '手机', py: 'shǒujī', mean: '휴대폰' },
      { ch: '打电话', py: 'dǎ diànhuà', mean: '전화하다' },
      { ch: '电视', py: 'diànshì', mean: '텔레비전' },
    ],
  },

  {
    id: 3,
    title: '3) 동작',
    icon: '🏃',
    words: [
      { ch: '买', py: 'mǎi', mean: '사다' },
      { ch: '卖', py: 'mài', mean: '팔다' },
      { ch: '穿', py: 'chuān', mean: '입다 (옷)' },
      { ch: '脱', py: 'tuō', mean: '벗다' },
      { ch: '关', py: 'guān', mean: '닫다' },
      { ch: '开', py: 'kāi', mean: '열다' },
      { ch: '做', py: 'zuò', mean: '하다, 만들다' },
      { ch: '学习', py: 'xuéxí', mean: '공부하다' },
      { ch: '工作', py: 'gōngzuò', mean: '일하다' },
      { ch: '旅游', py: 'lǚyóu', mean: '여행하다' },
      { ch: '点菜', py: 'diǎn cài', mean: '음식을 주문하다' },
      { ch: '喝咖啡', py: 'hē kāfēi', mean: '커피를 마시다' },
      { ch: '喝茶', py: 'hē chá', mean: '차를 마시다' },
      { ch: '喝酒', py: 'hē jiǔ', mean: '술을 마시다' },
      { ch: '喝水', py: 'hē shuǐ', mean: '물을 마시다' },
      { ch: '喝牛奶', py: 'hē niúnǎi', mean: '우유를 마시다' },
      { ch: '聊天儿', py: 'liáotiānr', mean: '수다 떨다' },
      { ch: '爬山', py: 'pá shān', mean: '등산하다' },
      { ch: '游泳', py: 'yóuyǒng', mean: '수영하다' },
      { ch: '滑雪', py: 'huáxuě', mean: '스키 타다' },
      { ch: '跑步', py: 'pǎobù', mean: '달리다' },
      { ch: '散步', py: 'sànbù', mean: '산책하다' },
      { ch: '运动', py: 'yùndòng', mean: '운동하다' },
      { ch: '玩电脑', py: 'wán diànnǎo', mean: '컴퓨터를 하다' },
      { ch: '打电话', py: 'dǎ diànhuà', mean: '전화하다' },
      { ch: '唱歌', py: 'chànggē', mean: '노래하다' },
      { ch: '跳舞', py: 'tiàowǔ', mean: '춤추다' },
      { ch: '听音乐', py: 'tīng yīnyuè', mean: '음악을 듣다' },
      { ch: '画画儿', py: 'huà huàr', mean: '그림을 그리다' },
      { ch: '玩游戏', py: 'wán yóuxì', mean: '게임하다' },
      { ch: '看书', py: 'kàn shū', mean: '책을 읽다' },
      { ch: '看电影', py: 'kàn diànyǐng', mean: '영화를 보다' },
      { ch: '看电视', py: 'kàn diànshì', mean: 'TV를 보다' },
      { ch: '看报纸', py: 'kàn bàozhǐ', mean: '신문을 보다' },
      { ch: '看杂志', py: 'kàn zázhì', mean: '잡지를 보다' },
      { ch: '看小说', py: 'kàn xiǎoshuō', mean: '소설을 읽다' },
      { ch: '打篮球', py: 'dǎ lánqiú', mean: '농구하다' },
      { ch: '打羽毛球', py: 'dǎ yǔmáoqiú', mean: '배드민턴 치다' },
      { ch: '打网球', py: 'dǎ wǎngqiú', mean: '테니스 치다' },
      { ch: '打棒球', py: 'dǎ bàngqiú', mean: '야구하다' },
      { ch: '踢足球', py: 'tī zúqiú', mean: '축구하다' },
      { ch: '坐公共汽车', py: 'zuò gōnggòng qìchē', mean: '버스를 타다' },
      { ch: '坐出租车', py: 'zuò chūzūchē', mean: '택시를 타다' },
      { ch: '坐地铁', py: 'zuò dìtiě', mean: '지하철을 타다' },
      { ch: '骑马', py: 'qí mǎ', mean: '말을 타다' },
      { ch: '骑自行车', py: 'qí zìxíngchē', mean: '자전거를 타다' },
      { ch: '骑摩托车', py: 'qí mótuōchē', mean: '오토바이를 타다' },
      { ch: '上车', py: 'shàng chē', mean: '차에 타다' },
      { ch: '开车', py: 'kāi chē', mean: '운전하다' },
      { ch: '起床', py: 'qǐchuáng', mean: '일어나다' },
      { ch: '睡觉', py: 'shuìjiào', mean: '잠자다' },
      { ch: '做菜', py: 'zuò cài', mean: '요리하다' },
      { ch: '做饭', py: 'zuò fàn', mean: '밥하다' },
      { ch: '吃饭', py: 'chī fàn', mean: '밥 먹다' },
      { ch: '洗手', py: 'xǐ shǒu', mean: '손을 씻다' },
      { ch: '洗脸', py: 'xǐ liǎn', mean: '세수하다' },
      { ch: '洗碗', py: 'xǐ wǎn', mean: '설거지하다' },
      { ch: '洗澡', py: 'xǐ zǎo', mean: '목욕하다' },
      { ch: '刷牙', py: 'shuā yá', mean: '이를 닦다' },
      { ch: '戴帽子', py: 'dài màozi', mean: '모자를 쓰다' },
      { ch: '上课', py: 'shàng kè', mean: '수업하다' },
      { ch: '下课', py: 'xià kè', mean: '수업이 끝나다' },
      { ch: '上班', py: 'shàng bān', mean: '출근하다' },
      { ch: '下班', py: 'xià bān', mean: '퇴근하다' },
      { ch: '上学', py: 'shàng xué', mean: '학교에 가다' },
      { ch: '毕业', py: 'bìyè', mean: '졸업하다' },
      { ch: '买菜', py: 'mǎi cài', mean: '장을 보다' },
      { ch: '买礼物', py: 'mǎi lǐwù', mean: '선물을 사다' },
      { ch: '买东西', py: 'mǎi dōngxī', mean: '물건을 사다' },
      { ch: '关门', py: 'guān mén', mean: '문을 닫다' },
      { ch: '开门', py: 'kāi mén', mean: '문을 열다' },
      { ch: '结束', py: 'jiéshù', mean: '끝내다, 종료하다' },
    ],
  },
  {
    id: 4,
    title: '4) 비교문 (명사/형용사)',
    icon: '⚖️',
    words: [
      // --- (1) 명사 ---
      { ch: '谁', py: 'shéi', mean: '누구' },
      { ch: '哪', py: 'nǎ', mean: '어느' },
      { ch: '自行车', py: 'zìxíngchē', mean: '자전거' },
      { ch: '出租车', py: 'chūzūchē', mean: '택시' },
      {
        ch: '公共汽车(公交车)',
        py: 'gōnggòng qìchē (gōngjiāochē)',
        mean: '버스',
      },
      { ch: '飞机', py: 'fēijī', mean: '비행기' },
      { ch: '火车', py: 'huǒchē', mean: '기차' },
      { ch: '地铁', py: 'dìtiě', mean: '지하철' },
      { ch: '大衣', py: 'dàyī', mean: '코트' },
      { ch: '东西', py: 'dōngxī', mean: '물건' },
      { ch: '毛衣', py: 'máoyī', mean: '스웨터' },
      { ch: '衬衫', py: 'chènshān', mean: '셔츠' },
      { ch: '帽子', py: 'màozi', mean: '모자' },
      { ch: '裙子', py: 'qúnzi', mean: '치마' },
      { ch: '裤子', py: 'kùzi', mean: '바지' },
      { ch: '袜子', py: 'wàzi', mean: '양말' },
      { ch: '运动鞋', py: 'yùndòngxié', mean: '운동화' },
      { ch: '皮鞋', py: 'píxié', mean: '구두' },
      { ch: '雨伞', py: 'yǔsǎn', mean: '우산' },
      { ch: '手表', py: 'shǒubiǎo', mean: '손목시계' },
      { ch: '钱包', py: 'qiánbāo', mean: '지갑' },
      { ch: '领带', py: 'lǐngdài', mean: '넥타이' },
      { ch: '围巾', py: 'wéijīn', mean: '목도리' },
      { ch: '耳环', py: 'ěrhuán', mean: '귀걸이' },
      { ch: '矿泉水', py: 'kuàngquánshuǐ', mean: '생수' },
      { ch: '咖啡', py: 'kāfēi', mean: '커피' },
      { ch: '可乐', py: 'kělè', mean: '콜라' },
      { ch: '雪碧', py: 'xuěbì', mean: '스프라이트' },
      { ch: '果汁', py: 'guǒzhī', mean: '주스' },
      { ch: '牛奶', py: 'niúnǎi', mean: '우유' },
      { ch: '茶', py: 'chá', mean: '차' },
      { ch: '水果', py: 'shuǐguǒ', mean: '과일' },
      { ch: '苹果', py: 'píngguǒ', mean: '사과' },
      { ch: '橘子', py: 'júzi', mean: '귤' },
      { ch: '梨', py: 'lí', mean: '배' },
      { ch: '西瓜', py: 'xīguā', mean: '수박' },
      { ch: '葡萄', py: 'pútao', mean: '포도' },
      { ch: '香蕉', py: 'xiāngjiāo', mean: '바나나' },
      { ch: '橙子', py: 'chéngzi', mean: '오렌지' },
      { ch: '甜瓜', py: 'tiánguā', mean: '멜론' },
      { ch: '草莓', py: 'cǎoméi', mean: '딸기' },
      { ch: '书包', py: 'shūbāo', mean: '가방(책가방)' },
      { ch: '本子', py: 'běnzi', mean: '공책' },
      { ch: '圆珠笔', py: 'yuánzhūbǐ', mean: '볼펜' },
      { ch: '铅笔', py: 'qiānbǐ', mean: '연필' },
      { ch: '橡皮', py: 'xiàngpí', mean: '지우개' },
      { ch: '尺子', py: 'chǐzi', mean: '자' },
      { ch: '桌子', py: 'zhuōzi', mean: '책상' },
      { ch: '椅子', py: 'yǐzi', mean: '의자' },
      { ch: '项链', py: 'xiàngliàn', mean: '목걸이' },
      { ch: '戒指', py: 'jièzhi', mean: '반지' },
      { ch: '手提包', py: 'shǒutíbāo', mean: '핸드백' },
      { ch: '礼物', py: 'lǐwù', mean: '선물' },
      { ch: '手机', py: 'shǒujī', mean: '휴대전화' },
      { ch: '笔记本电脑', py: 'bǐjìběn diànnǎo', mean: '노트북' },
      { ch: '个子', py: 'gèzi', mean: '키(신장)' },
      { ch: '书', py: 'shū', mean: '책' },
      { ch: '词典', py: 'cídiǎn', mean: '사전' },
      { ch: '篮球', py: 'lánqiú', mean: '농구' },
      { ch: '棒球', py: 'bàngqiú', mean: '야구' },
      { ch: '足球', py: 'zúqiú', mean: '축구' },
      { ch: '年龄', py: 'niánlíng', mean: '나이' },

      // --- (2) 형용사 ---
      { ch: '大', py: 'dà', mean: '크다' },
      { ch: '小', py: 'xiǎo', mean: '작다' },
      { ch: '多', py: 'duō', mean: '많다' },
      { ch: '少', py: 'shǎo', mean: '적다' },
      { ch: '长', py: 'cháng', mean: '길다' },
      { ch: '短', py: 'duǎn', mean: '짧다' },
      { ch: '宽', py: 'kuān', mean: '넓다' },
      { ch: '窄', py: 'zhǎi', mean: '좁다' },
      { ch: '年轻', py: 'niánqīng', mean: '젊다' },
      { ch: '老', py: 'lǎo', mean: '늙다, 나이가 많다' },
      { ch: '贵', py: 'guì', mean: '비싸다' },
      { ch: '便宜', py: 'piányi', mean: '싸다' },
      { ch: '重', py: 'zhòng', mean: '무겁다' },
      { ch: '轻', py: 'qīng', mean: '가볍다' },
      { ch: '冷', py: 'lěng', mean: '춥다' },
      { ch: '热', py: 'rè', mean: '덥다' },
      { ch: '高', py: 'gāo', mean: '높다, 키가 크다' },
      { ch: '矮', py: 'ǎi', mean: '키가 작다' },
      { ch: '低', py: 'dī', mean: '낮다' },
      { ch: '胖', py: 'pàng', mean: '뚱뚱하다' },
      { ch: '瘦', py: 'shòu', mean: '마르다' },
      { ch: '快', py: 'kuài', mean: '빠르다' },
      { ch: '慢', py: 'màn', mean: '느리다' },
      { ch: '早', py: 'zǎo', mean: '이르다' },
      { ch: '晚', py: 'wǎn', mean: '늦다' },
      { ch: '旧', py: 'jiù', mean: '오래되다' },
      { ch: '新', py: 'xīn', mean: '새롭다' },
      { ch: '累', py: 'lèi', mean: '피곤하다' },
      { ch: '困', py: 'kùn', mean: '졸리다' },
    ],
  },
  {
    id: 5,
    title: '5) 숫자 (시간/화폐/번호)',
    icon: '🔢',
    words: [
      // --- (1) 숫자 ---
      { ch: '零', py: 'líng', mean: '0' },
      { ch: '一', py: 'yī', mean: '1' },
      { ch: '二', py: 'èr', mean: '2' },
      { ch: '三', py: 'sān', mean: '3' },
      { ch: '四', py: 'sì', mean: '4' },
      { ch: '五', py: 'wǔ', mean: '5' },
      { ch: '六', py: 'liù', mean: '6' },
      { ch: '七', py: 'qī', mean: '7' },
      { ch: '八', py: 'bā', mean: '8' },
      { ch: '九', py: 'jiǔ', mean: '9' },
      { ch: '十', py: 'shí', mean: '10' },
      { ch: '一百', py: 'yì bǎi', mean: '100' },
      { ch: '一千', py: 'yì qiān', mean: '1,000' },
      { ch: '一万', py: 'yí wàn', mean: '10,000' },

      // --- (2) 번호, 층, 방번호 ---
      { ch: '号', py: 'hào', mean: '번호' },
      { ch: '号码', py: 'hàomǎ', mean: '번호' },
      { ch: '电话号码', py: 'diànhuà hàomǎ', mean: '전화번호' },
      { ch: '手机号码', py: 'shǒujī hàomǎ', mean: '휴대전화 번호' },
      { ch: '多少', py: 'duōshao', mean: '얼마, 몇' },
      { ch: '楼', py: 'lóu', mean: '건물, 층' },
      { ch: '层', py: 'céng', mean: '층' },
      { ch: '栋', py: 'dòng', mean: '동(건물 단위)' },
      { ch: '路', py: 'lù', mean: '길, 도로' },

      // --- (3) 시간 ---
      { ch: '现在', py: 'xiànzài', mean: '지금' },
      { ch: '几', py: 'jǐ', mean: '몇' },
      { ch: '点', py: 'diǎn', mean: '시' },
      { ch: '分', py: 'fēn', mean: '분' },
      { ch: '分钟', py: 'fēnzhōng', mean: '분(시간 단위)' },
      { ch: '四点(零)五分', py: 'sì diǎn (líng) wǔ fēn', mean: '4시 5분' },
      { ch: '两点', py: 'liǎng diǎn', mean: '2시' },
      { ch: '半', py: 'bàn', mean: '반' },
      { ch: '十点半', py: 'shí diǎn bàn', mean: '10시 반' },
      { ch: '刻', py: 'kè', mean: '15분' },
      { ch: '十二点一刻', py: "shí'èr diǎn yí kè", mean: '12시 15분' },
      { ch: '差', py: 'chà', mean: '~분 전' },
      { ch: '差五分三点', py: 'chà wǔ fēn sān diǎn', mean: '3시 5분 전' },
      { ch: '早上', py: 'zǎoshang', mean: '아침' },
      { ch: '晚上', py: 'wǎnshang', mean: '저녁, 밤' },
      { ch: '上午', py: 'shàngwǔ', mean: '오전' },
      { ch: '中午', py: 'zhōngwǔ', mean: '정오' },
      { ch: '下午', py: 'xiàwǔ', mean: '오후' },

      // --- (4) 시간 관련 동사 ---
      { ch: '开始', py: 'kāishǐ', mean: '시작하다' },
      { ch: '结束', py: 'jiéshù', mean: '끝나다, 종료하다' },
      { ch: '开门', py: 'kāi mén', mean: '문을 열다' },
      { ch: '关门', py: 'guān mén', mean: '문을 닫다' },

      // --- (5) 시간 관련 명사 ---
      { ch: '比赛', py: 'bǐsài', mean: '경기' },
      { ch: '音乐会', py: 'yīnyuèhuì', mean: '음악회' },
      { ch: '演唱会', py: 'yǎnchànghuì', mean: '콘서트' },
      { ch: '表演', py: 'biǎoyǎn', mean: '공연' },
      { ch: '考试', py: 'kǎoshì', mean: '시험' },
      { ch: '电影', py: 'diànyǐng', mean: '영화' },

      // --- (6) 화폐 ---
      { ch: '块（=元）', py: 'kuài (yuán)', mean: '위안(중국 화폐 단위)' },
      { ch: '毛（=角）', py: 'máo (jiǎo)', mean: '0.1위안' },
      { ch: '分', py: 'fēn', mean: '0.01위안' },

      // --- (7) 가격 묻고 답하기 관련 표현 ---
      { ch: '一块', py: 'yí kuài', mean: '1위안' },
      { ch: '五块', py: 'wǔ kuài', mean: '5위안' },
      { ch: '十块', py: 'shí kuài', mean: '10위안' },
      { ch: '二十块', py: 'èrshí kuài', mean: '20위안' },
      { ch: '一百块', py: 'yì bǎi kuài', mean: '100위안' },
      { ch: '两百块', py: 'liǎng bǎi kuài', mean: '200위안' },
      { ch: '多少钱', py: 'duōshao qián', mean: '얼마입니까' },
      { ch: '价格', py: 'jiàgé', mean: '가격' },
      { ch: '价钱', py: 'jiàqián', mean: '가격' },
      { ch: '人民币', py: 'rénmínbì', mean: '인민폐' },

      // --- (8) 가격 묻기에 자주 등장하는 명사 ---
      { ch: '运动鞋', py: 'yùndòngxié', mean: '운동화' },
      { ch: '帽子', py: 'màozi', mean: '모자' },
      { ch: '眼镜', py: 'yǎnjìng', mean: '안경' },
      { ch: '手表', py: 'shǒubiǎo', mean: '손목시계' },
      { ch: '手机', py: 'shǒujī', mean: '휴대전화' },
      { ch: '电影票', py: 'diànyǐng piào', mean: '영화표' },
      { ch: '笔记本电脑', py: 'bǐjìběn diànnǎo', mean: '노트북' },
      { ch: '电脑', py: 'diànnǎo', mean: '컴퓨터' },
      { ch: '圆珠笔', py: 'yuánzhūbǐ', mean: '볼펜' },
      { ch: '皮包', py: 'píbāo', mean: '가죽가방' },
      { ch: '书包', py: 'shūbāo', mean: '책가방' },
      { ch: '牛奶', py: 'niúnǎi', mean: '우유' },
      { ch: '咖啡', py: 'kāfēi', mean: '커피' },
      { ch: '果汁', py: 'guǒzhī', mean: '주스' },
    ],
  },
  {
    id: 6,
    title: '6) 도량형 (길이/무게/온도)',
    icon: '📏',
    words: [
      // --- (1) 길이 도량형 ---
      { ch: '有', py: 'yǒu', mean: '~만큼 되다, ~만하다' },
      { ch: '多', py: 'duō', mean: '얼마나, 많다' },
      { ch: '离', py: 'lí', mean: '~에서, ~로부터' },
      { ch: '个子', py: 'gèzi', mean: '키' },
      { ch: '身高', py: 'shēngāo', mean: '신장' },
      { ch: '米', py: 'mǐ', mean: '미터' },
      { ch: '厘米', py: 'límǐ', mean: '센티미터(cm)' },
      { ch: '公里', py: 'gōnglǐ', mean: '킬로미터(km)' },
      { ch: '楼', py: 'lóu', mean: '층, 건물' },
      { ch: '大厦', py: 'dàshà', mean: '빌딩' },
      { ch: '高', py: 'gāo', mean: '높다' },
      { ch: '低', py: 'dī', mean: '낮다' },
      { ch: '长', py: 'cháng', mean: '길다' },
      { ch: '短', py: 'duǎn', mean: '짧다' },
      { ch: '远', py: 'yuǎn', mean: '멀다' },
      { ch: '近', py: 'jìn', mean: '가깝다' },
      { ch: '距离', py: 'jùlí', mean: '거리' },

      // --- (2) 무게 도량형 ---
      { ch: '体重', py: 'tǐzhòng', mean: '체중' },
      { ch: '公斤', py: 'gōngjīn', mean: '킬로그램(kg)' },
      { ch: '斤', py: 'jīn', mean: '근' },
      { ch: '克', py: 'kè', mean: '그램(g)' },
      { ch: '吨', py: 'dūn', mean: '톤(ton)' },
      { ch: '轻', py: 'qīng', mean: '가볍다' },
      { ch: '重', py: 'zhòng', mean: '무겁다' },
      { ch: '行李', py: 'xíngli', mean: '짐' },
      { ch: '超重', py: 'chāozhòng', mean: '초과하다' },
      { ch: '不够', py: 'búgòu', mean: '부족하다, 모자라다' },

      // --- (3) 온도 ---
      { ch: '温度', py: 'wēndù', mean: '온도' },
      { ch: '度', py: 'dù', mean: '도' },
      { ch: '气温', py: 'qìwēn', mean: '기온' },
      { ch: '冷', py: 'lěng', mean: '춥다' },
      { ch: '热', py: 'rè', mean: '덥다' },
      { ch: '摄氏度', py: 'shèshìdù', mean: '섭씨' },
      { ch: '体温', py: 'tǐwēn', mean: '체온' },
      { ch: '高', py: 'gāo', mean: '높다' },
      { ch: '低', py: 'dī', mean: '낮다' },
      { ch: '温暖', py: 'wēnnuǎn', mean: '따뜻하다' },
    ],
  },
];
